# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!
pod 'Mantle' 
pod 'LBBlurredImage' 
pod 'TSMessages' 
pod 'ReactiveCocoa'
target 'weatherAPP' do

end

target 'weatherAPPTests' do

end

target 'weatherAPPUITests' do

end

